package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Controller.BulletinBoardController;
import Controller.ThreadController;
import Model.OneDeletedTopicToken;
import Model.OneMessage;
import Model.OneTopic;
import java.awt.Color;
import java.rmi.RemoteException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.jini.core.event.RemoteEvent;
import net.jini.core.event.RemoteEventListener;
import net.jini.core.event.UnknownEventException;
import net.jini.space.AvailabilityEvent;

/**
 * Bulletin Board Form
 *
 * @author Hamza Saeed - u1550400
 */
public class frmBulletinBoard extends javax.swing.JFrame {

    BulletinBoardController BulletinBoardController;
    //models for JTable displaying topics and notifications
    DefaultTableModel topicModel;
    DefaultTableModel notifsModel;
    //Holds list of topics
    ArrayList<OneTopic> topics;
    int lastButtonPress;

    /**
     * Creates new form frmBulletinBoard
     */
    public frmBulletinBoard() {
        initComponents();
    }

    public frmBulletinBoard(BulletinBoardController bulletinBoardController) {
        initComponents();
        //set window to middle of screen
        this.setLocationRelativeTo(null);
        //initialise controller variable
        BulletinBoardController = bulletinBoardController;
        //Display username
        lblName.setText("Logged in as: " + BulletinBoardController.Settings.currentUser.getName());
        //initialise variables
        topics = new ArrayList<OneTopic>();
        topicModel = (DefaultTableModel) topicTable.getModel();
        notifsModel = (DefaultTableModel) notifTable.getModel();
        //retrieves all topics posted
        BulletinBoardController.retrieveTopics(topics, topicModel);
        //retrieves potential notifications of updated subscribed topics whilst user has been offline
        BulletinBoardController.getNotifications(notifsModel, lblNotifications);
        //retrieves potential notifications of subscribed topic deletion whilst user has been offline
        BulletinBoardController.notifyAllDeletes(notifsModel, lblNotifications);
        //registers new topics for notifications and defines behaviour for when new topic is added.
        BulletinBoardController.listenForTopicsAndNotify(topics, topicModel);
        //registers new messages for notifications and defines behaviour for when new msg for subscribed topic is added.
        BulletinBoardController.listenForMessagesAndNotify(notifsModel, lblNotifications);
        //registers new deletions for notifications and defines behaviour for when new deletion token is added
        BulletinBoardController.listenForDeletionAndNotify(notifsModel, topicModel, topics, lblNotifications);
        lastButtonPress = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        sideMenu = new javax.swing.JPanel();
        btnViewTopicsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNotificationsPanel = new javax.swing.JPanel();
        lblNotifications = new javax.swing.JLabel();
        btnMyAccountPanel = new javax.swing.JPanel();
        lblAccount = new javax.swing.JLabel();
        btnMyAccountPanel1 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        titleBar = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        ViewTopicPanel = new javax.swing.JPanel();
        TopicsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        topicTable = new javax.swing.JTable();
        txtNewTopic = new javax.swing.JTextField();
        btnAddNewTopic = new javax.swing.JButton();
        btnGoToThread = new javax.swing.JButton();
        btnDeleteTopic = new javax.swing.JButton();
        NotificationPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        notifTable = new javax.swing.JTable();
        MyAccountPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCurrentPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtNewPasswordConfirmation = new javax.swing.JPasswordField();
        btnChangePassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideMenu.setBackground(new java.awt.Color(22, 160, 133));
        sideMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewTopicsPanel.setBackground(new java.awt.Color(22, 186, 149));
        btnViewTopicsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewTopicsPanelMousePressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Topics");

        javax.swing.GroupLayout btnViewTopicsPanelLayout = new javax.swing.GroupLayout(btnViewTopicsPanel);
        btnViewTopicsPanel.setLayout(btnViewTopicsPanelLayout);
        btnViewTopicsPanelLayout.setHorizontalGroup(
            btnViewTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnViewTopicsPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        btnViewTopicsPanelLayout.setVerticalGroup(
            btnViewTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        sideMenu.add(btnViewTopicsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));
        btnViewTopicsPanel.getAccessibleContext().setAccessibleDescription("");

        btnNotificationsPanel.setBackground(new java.awt.Color(22, 160, 133));
        btnNotificationsPanel.setPreferredSize(new java.awt.Dimension(260, 48));
        btnNotificationsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNotificationsPanelMousePressed(evt);
            }
        });

        lblNotifications.setForeground(new java.awt.Color(255, 255, 255));
        lblNotifications.setText("Notifications");

        javax.swing.GroupLayout btnNotificationsPanelLayout = new javax.swing.GroupLayout(btnNotificationsPanel);
        btnNotificationsPanel.setLayout(btnNotificationsPanelLayout);
        btnNotificationsPanelLayout.setHorizontalGroup(
            btnNotificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnNotificationsPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lblNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        btnNotificationsPanelLayout.setVerticalGroup(
            btnNotificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNotifications, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        sideMenu.add(btnNotificationsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 168, -1, -1));

        btnMyAccountPanel.setBackground(new java.awt.Color(22, 160, 133));
        btnMyAccountPanel.setPreferredSize(new java.awt.Dimension(260, 48));
        btnMyAccountPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMyAccountPanelMousePressed(evt);
            }
        });

        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount.setText("My Account");

        javax.swing.GroupLayout btnMyAccountPanelLayout = new javax.swing.GroupLayout(btnMyAccountPanel);
        btnMyAccountPanel.setLayout(btnMyAccountPanelLayout);
        btnMyAccountPanelLayout.setHorizontalGroup(
            btnMyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMyAccountPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        btnMyAccountPanelLayout.setVerticalGroup(
            btnMyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        sideMenu.add(btnMyAccountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 218, -1, -1));

        btnMyAccountPanel1.setBackground(new java.awt.Color(22, 160, 133));
        btnMyAccountPanel1.setPreferredSize(new java.awt.Dimension(260, 48));
        btnMyAccountPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMyAccountPanel1MousePressed(evt);
            }
        });

        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("Exit");

        javax.swing.GroupLayout btnMyAccountPanel1Layout = new javax.swing.GroupLayout(btnMyAccountPanel1);
        btnMyAccountPanel1.setLayout(btnMyAccountPanel1Layout);
        btnMyAccountPanel1Layout.setHorizontalGroup(
            btnMyAccountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMyAccountPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        btnMyAccountPanel1Layout.setVerticalGroup(
            btnMyAccountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        sideMenu.add(btnMyAccountPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        back.add(sideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 260, 470));

        titleBar.setBackground(new java.awt.Color(22, 185, 136));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Your Name");

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        back.add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 0, 770, 110));
        titleBar.getAccessibleContext().setAccessibleName("");
        titleBar.getAccessibleContext().setAccessibleDescription("");

        mainPanel.setLayout(new java.awt.CardLayout());

        ViewTopicPanel.setBackground(new java.awt.Color(255, 255, 255));
        ViewTopicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topicTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Topic", "User", "DateTime"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        topicTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        topicTable.setAutoscrolls(false);
        jScrollPane2.setViewportView(topicTable);

        javax.swing.GroupLayout TopicsPanelLayout = new javax.swing.GroupLayout(TopicsPanel);
        TopicsPanel.setLayout(TopicsPanelLayout);
        TopicsPanelLayout.setHorizontalGroup(
            TopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopicsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addContainerGap())
        );
        TopicsPanelLayout.setVerticalGroup(
            TopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopicsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        ViewTopicPanel.add(TopicsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 9, 726, 290));
        ViewTopicPanel.add(txtNewTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 314, 360, -1));

        btnAddNewTopic.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnAddNewTopic.setText("Add New Topic");
        btnAddNewTopic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewTopicMouseClicked(evt);
            }
        });
        ViewTopicPanel.add(btnAddNewTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 110, -1));

        btnGoToThread.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnGoToThread.setText("Go to Thread");
        btnGoToThread.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoToThreadMouseClicked(evt);
            }
        });
        ViewTopicPanel.add(btnGoToThread, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 110, -1));

        btnDeleteTopic.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnDeleteTopic.setText("Delete Topic");
        btnDeleteTopic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteTopicMouseClicked(evt);
            }
        });
        ViewTopicPanel.add(btnDeleteTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        mainPanel.add(ViewTopicPanel, "card2");

        NotificationPanel.setBackground(new java.awt.Color(255, 255, 255));

        notifTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Topic Updated", "User", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        notifTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        notifTable.setAutoscrolls(false);
        jScrollPane3.setViewportView(notifTable);

        javax.swing.GroupLayout NotificationPanelLayout = new javax.swing.GroupLayout(NotificationPanel);
        NotificationPanel.setLayout(NotificationPanelLayout);
        NotificationPanelLayout.setHorizontalGroup(
            NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NotificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addContainerGap())
        );
        NotificationPanelLayout.setVerticalGroup(
            NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        mainPanel.add(NotificationPanel, "card4");

        MyAccountPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Current Password");

        jLabel3.setText("New Password");

        jLabel4.setText("Confirm");

        btnChangePassword.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnChangePassword.setText("Change Password");
        btnChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangePasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MyAccountPanelLayout = new javax.swing.GroupLayout(MyAccountPanel);
        MyAccountPanel.setLayout(MyAccountPanelLayout);
        MyAccountPanelLayout.setHorizontalGroup(
            MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(92, 92, 92)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(txtCurrentPassword)
                    .addComponent(txtNewPassword)
                    .addComponent(txtNewPasswordConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        MyAccountPanelLayout.setVerticalGroup(
            MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNewPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnChangePassword)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        mainPanel.add(MyAccountPanel, "card4");

        back.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 750, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTopicsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewTopicsPanelMousePressed
        //loads new panel when pressed
        ViewTopicPanel.setVisible(true);
        NotificationPanel.setVisible(false);
        MyAccountPanel.setVisible(false);
        //changes colour so user can see which panel is selected
        setColour(btnViewTopicsPanel);
        resetColour(btnNotificationsPanel);
        resetColour(btnMyAccountPanel);
        //disable current so it can't be pressed twice and enable previous
        btnViewTopicsPanel.setEnabled(false);
        btnNotificationsPanel.setEnabled(true);
        btnMyAccountPanel.setEnabled(true);

        //if notifications accessed, clear notifications
        if (lastButtonPress == 1) {
            //call method to update last notification access time in space
            BulletinBoardController.updateNotificationLastAccess();
            notifsModel.setRowCount(0);
            //update label
            lblNotifications.setText("Notifications (" + notifsModel.getRowCount() + ")");
        }
        lastButtonPress = 0;
    }//GEN-LAST:event_btnViewTopicsPanelMousePressed


    private void btnNotificationsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotificationsPanelMousePressed
        //loads new panel when pressed
        ViewTopicPanel.setVisible(false);
        MyAccountPanel.setVisible(false);
        NotificationPanel.setVisible(true);
        //changes colour so user can see which panel is selected
        resetColour(btnViewTopicsPanel);
        resetColour(btnMyAccountPanel);
        setColour(btnNotificationsPanel);
        //disable current so it can't be pressed twice and enable previous
        btnViewTopicsPanel.setEnabled(true);
        btnMyAccountPanel.setEnabled(true);
        btnNotificationsPanel.setEnabled(false);
        lastButtonPress = 1;
    }//GEN-LAST:event_btnNotificationsPanelMousePressed


    private void btnAddNewTopicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewTopicMouseClicked

        String newTopicTitle = txtNewTopic.getText();
        if (BulletinBoardController.validateNewTopic(newTopicTitle)) {
            //reset textbox
            txtNewTopic.setText("");
        }
    }//GEN-LAST:event_btnAddNewTopicMouseClicked

    private void btnGoToThreadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoToThreadMouseClicked
    
        //ensure row is selected
        if (topicTable.getSelectedRow() != -1) {
            //Create ThreadController for Thread form
            ThreadController threadController = new ThreadController(BulletinBoardController.Settings);
            //open thread form passing in the sufficient parameters so that correct topic is opened
            frmThread thread = new frmThread(topics, topicTable.getSelectedRow(), threadController);
            thread.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Select a topic to view from the table", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGoToThreadMouseClicked

    private void btnDeleteTopicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteTopicMouseClicked

        //ensure row is selected
        if (topicTable.getSelectedRow() != -1) {
            //get topic for selected row
            OneTopic chosenTopic = topics.get(topicTable.getSelectedRow());
            //ensure current user is topic owner
            if (BulletinBoardController.Settings.currentUser.getName().equals(chosenTopic.getOwner().getName())) {
                //if so, write deleted topic token and delete topic
                BulletinBoardController.writeDeletedTopicToken(chosenTopic, topicTable.getSelectedRow());
                BulletinBoardController.deleteTopic(chosenTopic.getTopicID());
                JOptionPane.showMessageDialog(null, "Deletion successful");
            } else {
                JOptionPane.showMessageDialog(null, "Deletion failed. You are not the owner of this topic.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a topic to delete", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteTopicMouseClicked

    private void btnMyAccountPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMyAccountPanelMousePressed
        //loads new panel when pressed
        ViewTopicPanel.setVisible(false);
        NotificationPanel.setVisible(false);
        MyAccountPanel.setVisible(true);
        //changes colour so user can see which panel is selected
        resetColour(btnViewTopicsPanel);
        resetColour(btnNotificationsPanel);
        setColour(btnMyAccountPanel);

        //disable current so it can't be pressed twice and enable previous
        btnMyAccountPanel.setEnabled(false);
        btnViewTopicsPanel.setEnabled(true);
        btnNotificationsPanel.setEnabled(true);

        //if notifications accessed, clear notifications
        if (lastButtonPress == 1) {
            //call method to update last notification access time in space
            BulletinBoardController.updateNotificationLastAccess();
            notifsModel.setRowCount(0);
            //update label
            lblNotifications.setText("Notifications (" + notifsModel.getRowCount() + ")");
        }
        lastButtonPress = 2;
    }//GEN-LAST:event_btnMyAccountPanelMousePressed

    private void btnChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePasswordMouseClicked
        //put password variables into string
        String currentPassword = String.valueOf(txtCurrentPassword.getPassword());
        String newPassword = String.valueOf(txtNewPassword.getPassword());
        String confirmedNewPassword = String.valueOf(txtNewPasswordConfirmation.getPassword());
        //call method to check password is valid and change if so
        BulletinBoardController.verifyPasswordChange(currentPassword, newPassword, confirmedNewPassword);
        
    }//GEN-LAST:event_btnChangePasswordMouseClicked

    private void btnMyAccountPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMyAccountPanel1MousePressed
        System.exit(0);
    }//GEN-LAST:event_btnMyAccountPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBulletinBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBulletinBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBulletinBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBulletinBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBulletinBoard().setVisible(true);
            }
        });

    }

    void setColour(JPanel panel) {
        panel.setBackground(new Color(22, 186, 149));
    }

    void resetColour(JPanel panel) {
        panel.setBackground(new Color(22, 160, 133));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MyAccountPanel;
    private javax.swing.JPanel NotificationPanel;
    private javax.swing.JPanel TopicsPanel;
    private javax.swing.JPanel ViewTopicPanel;
    private javax.swing.JPanel back;
    private javax.swing.JButton btnAddNewTopic;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDeleteTopic;
    private javax.swing.JButton btnGoToThread;
    private javax.swing.JPanel btnMyAccountPanel;
    private javax.swing.JPanel btnMyAccountPanel1;
    private javax.swing.JPanel btnNotificationsPanel;
    private javax.swing.JPanel btnViewTopicsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNotifications;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable notifTable;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JPanel titleBar;
    private javax.swing.JTable topicTable;
    private javax.swing.JPasswordField txtCurrentPassword;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtNewPasswordConfirmation;
    private javax.swing.JTextField txtNewTopic;
    // End of variables declaration//GEN-END:variables

}
